### ISSUE TITLE
Launch Editor button not working 

### ISSUE THREAD

**Issue by ckonher-webworld** [jaredkrinke/learn-scheme#1]
Hello, 

The Launch Editor doesn't seem to be working. 

Could you please check? 

Regards, 

Chaitanya Konher

**Comment by ckonher-webworld** [comment]
My apologies, it's working just fine!!! Sorry. I edited the url from 'https' to 'http' and all good now. All set to learn Scheme. Thank you.. :-)

**Comment by jaredkrinke** [comment]
I'm going to reopen this because I should make sure *both* HTTP and HTTPS work.

**Comment by jaredkrinke** [comment]
Fix deployed
